-- Seed: top-60 useful English vocabulary words for EN language catalog
-- Stopwords excluded; these are practical A1-B1 level learnable words.
-- frequency_rank reflects approximate corpus frequency among content words.

INSERT INTO words (lemma, lang, part_of_speech, frequency_rank) VALUES
-- Nouns
('time',     'EN', 'noun', 1),
('year',     'EN', 'noun', 2),
('people',   'EN', 'noun', 3),
('way',      'EN', 'noun', 4),
('day',      'EN', 'noun', 5),
('man',      'EN', 'noun', 6),
('woman',    'EN', 'noun', 7),
('child',    'EN', 'noun', 8),
('world',    'EN', 'noun', 9),
('life',     'EN', 'noun', 10),
('hand',     'EN', 'noun', 11),
('place',    'EN', 'noun', 12),
('week',     'EN', 'noun', 13),
('company',  'EN', 'noun', 14),
('system',   'EN', 'noun', 15),
('city',     'EN', 'noun', 16),
('country',  'EN', 'noun', 17),
('family',   'EN', 'noun', 18),
('student',  'EN', 'noun', 19),
('school',   'EN', 'noun', 20),
-- Verbs
('know',     'EN', 'verb', 21),
('think',    'EN', 'verb', 22),
('take',     'EN', 'verb', 23),
('come',     'EN', 'verb', 24),
('give',     'EN', 'verb', 25),
('look',     'EN', 'verb', 26),
('want',     'EN', 'verb', 27),
('seem',     'EN', 'verb', 28),
('work',     'EN', 'verb', 29),
('tell',     'EN', 'verb', 30),
('call',     'EN', 'verb', 31),
('keep',     'EN', 'verb', 32),
('let',      'EN', 'verb', 33),
('try',      'EN', 'verb', 34),
('ask',      'EN', 'verb', 35),
('need',     'EN', 'verb', 36),
('feel',     'EN', 'verb', 37),
('become',   'EN', 'verb', 38),
('leave',    'EN', 'verb', 39),
('show',     'EN', 'verb', 40),
-- Adjectives
('good',     'EN', 'adjective', 41),
('new',      'EN', 'adjective', 42),
('first',    'EN', 'adjective', 43),
('last',     'EN', 'adjective', 44),
('long',     'EN', 'adjective', 45),
('great',    'EN', 'adjective', 46),
('little',   'EN', 'adjective', 47),
('own',      'EN', 'adjective', 48),
('right',    'EN', 'adjective', 49),
('old',      'EN', 'adjective', 50),
('big',      'EN', 'adjective', 51),
('high',     'EN', 'adjective', 52),
('different','EN', 'adjective', 53),
('small',    'EN', 'adjective', 54),
('large',    'EN', 'adjective', 55),
('next',     'EN', 'adjective', 56),
('early',    'EN', 'adjective', 57),
('young',    'EN', 'adjective', 58),
('important','EN', 'adjective', 59),
('public',   'EN', 'adjective', 60)
ON CONFLICT (lemma, lang) DO NOTHING;
